name: fluentui_emoji_icon
description: Flutter Icon Widget Package using FluentUI-Emoji published from Microsoft.
version: 0.0.1
homepage: https://github.com/sugitlab/fluentui_emoji_icon

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
