name: fluentui_emoji_icon
description: Flutter Icon Widget Package using FluentUI-Emoji published from Microsoft.
version: 0.0.2
homepage: https://github.com/sugitlab/fluentui_emoji_icon

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  recase: ^4.1.0
  rw_git: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
